apiVersion: idp.autopay.pl/v1alpha1
kind: Resource
metadata:
  labels:
    app.kubernetes.io/name: idp
    app.kubernetes.io/managed-by: kustomize
  name: resource-sample
spec:
  # TODO(user): Add fields here
