apiVersion: idp.autopay.pl/v1alpha1
kind: ResourceTemplate
metadata:
  name: kafka-topic
  namespace: idp-system
spec:
  displayName: Kafka topic
  description: Provisions a Kafka topic via Strimzi resources
  parameters:
    - name: tenant
      schema:
        type: string
        immutable: true
        optional: false
    - name: name
      schema:
        type: string
        immutable: true
        optional: false
    - name: replication
      schema:
        type: string
        immutable: false
        optional: true
        default: "3"
    - name: type
      schema:
        type: string
        immutable: false
        optional: true
  provisioning:
    git:
      repositoryURL: git@github.com:jjsiv/resources.git
      config:
        author:
          name: IDP Operator
          email: "operator@autopay.pl"
        auth:
          secretRef:
            name: git-auth
            key: private-key
      branch: master
      commitMessage: |
        Create Kafka topic for {{ .parameters.tenant }}
      templates:
        - path: "tenants/{{ .parameters.tenant }}/kafka-topics"
          filename: "{{ .parameters.name }}.yaml"
          content: |
            apiVersion: kafka.strimzi.io/v1
            kind: KafkaTopic
            metadata:
              name: {{ .parameters.name }}
              labels:
                strimzi.io/cluster: my-cluster
            spec:
              partitions: 1
              replicas: {{ .parameters.replication }}
              config:
                retention.ms: 7200000
                segment.bytes: 1073741824
  backstageCatalog:
    provisioning:
      git:
        repositoryURL: git@github.com:jjsiv/resources.git
        commitMessage: |
          Create catalog-info.yaml for {{ .parameters.tenant }}
        path: "tenants/{{ .parameters.tenant }}/kafka-topics/catalog-info.yaml"
        config:
          author:
            name: IDP Operator
            email: operator@autopay.pl
          auth:
            secretRef:
              name: git-auth
              key: private-key
        branch: master
    # template:
    #   metadata:
    #     name: kafka-topic-{{ .resource.name }}
    #   spec:
    #     type: kafka-topic
    #     dependsOn:
    #       - resource:default/kafka-cluster
