apiVersion: idp.autopay.pl/v1alpha1
kind: Resource
metadata:
  name: test-topic
  namespace: idp-system
spec:
  displayName: Test_Topic
  description: Test_Topic is used for testing Kafka topics
  ownerRef:
    kind: Tenant
    name: payments
  templateRef:
    name: kafka-topic
    namespace: idp-system
    parameters:
      - name: tenant
        value: payments
      - name: name
        value: Test_Topic
      - name: replication
        value: "5"
      - name: type
        value: private
