apiVersion: idp.autopay.pl/v1alpha1
kind: Tenant
metadata:
  name: payments
  namespace: idp-system
spec:
  displayName: Payments
  description: |
    Payments services
  identityProvider:
    okta:
      groups:
        - name: idp-payments-members
        - name: idp-payments-maintainers
          roles:
            - maintainer
  members:
    - email: a.b@autopay.pl
      entityName: a-b
      roles:
        - owner
        - maintainer
        - approver
    - email: c.d@autopay.pl
      entityName: c-d
      roles:
        - maintainer
    - email: f.g@autopay.pl
      entityName: f-g
      roles:
        - developer
    - email: h.j@autopay.pl
      entityName: h-j
      roles:
        - project-manager
  backstageCatalog:
    provisioning:
      git:
        repositoryURL: git@github.com:jjsiv/catalog.git
        branch: "refs/heads/master"
        commitMessage: "Create catalog-info.yaml"
        config:
          author:
            email: operator@autopay.pl
            name: IDP Operator
          auth:
            secretRef:
              name: git-auth
              key: private-key
        path: "{{ .tenant.name }}/catalog-info.yaml"
